version: 2.1

jobs:
  lint:
    docker:
      - image: node:16.11.1
        environment:
          TERM: xterm
          TZ: "America/New_York"

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-

      - run: yarn install --immutable

      - run:
          name: Run Linter
          command: yarn lint

      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/repo/node_modules
            - ~/.yarn

  unit_test:
    docker:
      - image: node:16.11.1
        environment:
          TERM: xterm
          TZ: "America/New_York"

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-

      - run: yarn install --immutable

      - run:
          name: Unit Test
          command: yarn test:coverage --runInBand

workflows:
  build:
    jobs:
      - lint:
          name: Lint
      - unit_test:
          name: Unit Tests
          requires:
            - Lint
